name: Run Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: set up node.js
      uses: actions/setup-node@v3
      with: 
        node-version: '18'
        cache: 'npm'

    - name: npm test
      run: |
        npm install
        npm test

  coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: '18'
        cache: 'npm'

    - name: Run tests with coverage
      run: |
        npm install
        npm test -- --coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/